server:
  port: ${PORT:${SERVER_PORT:8085}}

spring:
  application:
    name: ms-compra-service

  datasource:
    url: jdbc:h2:mem:ventasdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console


  feign:
    inventario:
      base-url: localhost:8086
    producto:
      base-url: localhost:8083
    proveedor:
      base-url: localhost:8082

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}